import common from './common';

export default {
  ...common,
  env: 'production',
  storefrontURL: '//storefront.templatemonster.com/',
  cookiesRoot: '.templatemonster.com',
  monsterURL: '//www.templatemonster.com/',
  authURL: '//account.templatemonster.com/',
  cabinetURL: '//account.templatemonster.com/',
  authServiceURL: '//api.templatemonster.com/oauth/',
  balancesServiceURL: '//api.templatemonster.com/balances/v2/',
  cartsServiceURL: '//api.templatemonster.com/carts/v1/',
  centrifugeCartURL: '//socket.templatemonster.com/',
  centrifugeNotificationsURL: '//ws.templatemonster.com',
  chatURL: '//chat.template-help.com/',
  collectionsServiceURL: '//api.templatemonster.com/collection/v2/',
  localesServiceURL: '//service-locales.templatemonster.com/api/v1/locales',
  membershipsServiceURL: '//api.templatemonster.com/memberships/v1/',
  navigationsServiceURL: '//api.templatemonster.com/navigations/v1/',
  notificationsServiceURL: '//api.templatemonster.com/notifications/v1/',
  ordersServiceURL: '//api.templatemonster.com/orders/v1/',
  productsServiceURL: '//api.templatemonster.com/products/v2/',
  reviewsServiceURL: '//api.templatemonster.com/reviews/v1/',
  servicesServiceURL: '//api.templatemonster.com/services/v1/',
  ticketsServiceURL: '//api.templatemonster.com/tickets/v1/',
  uploadsServiceURL: '//api.templatemonster.com/uploads/v1/',
  usersServiceURL: '//api.templatemonster.com/users/v1/',
  vendorsServiceURL: '//api.templatemonster.com/authors/v1/',
};
